### ISSUE TITLE
block main thread in ImagePickerSheetController.cellForItemAtIndexPath

### ISSUE THREAD

**Issue by iblacksun** [lbrndnr/ImagePickerSheetController#78] opened 2016-07-14 02:42 UTC
In method ```requestImageForAsset```, using ```requestOptions.synchronous = true``` to fetch asset image, when image is big, will block main thread, can't present the ```ImagePickerSheetController```

**Comment by lbrndnr** [comment] 2016-09-21 18:40
Duplicate of #62

**Closed by lbrndnr** 2016-09-21 18:40 UTC
